//! Command-level branch survey behavior.

#![expect(
    clippy::expect_used,
    reason = "a panicking assertion is the point of a test"
)]

use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicUsize, Ordering};

static NEXT_SCRATCH: AtomicUsize = AtomicUsize::new(0);

struct Scratch(PathBuf);

impl Scratch {
    fn new(label: &str) -> Self {
        let sequence = NEXT_SCRATCH.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "okf-adopt-{label}-{}-{sequence}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&path);
        std::fs::create_dir_all(&path).expect("scratch directory should be created");
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn write(path: &Path, text: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    std::fs::write(path, text).expect("fixture should be written");
}

fn git(root: &Path, args: &[&str]) -> String {
    let output = Command::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .expect("git should run");
    assert!(
        output.status.success(),
        "git {} failed: {}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout).trim().to_owned()
}

fn run(root: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_okf-adopt"))
        .args(args)
        .current_dir(root)
        .output()
        .expect("okf-adopt should run")
}

fn initialize(root: &Path) {
    git(root, &["init", "--quiet", "--initial-branch=main"]);
    git(root, &["config", "user.email", "fixture@example.invalid"]);
    git(root, &["config", "user.name", "Fixture"]);
    write(
        &root.join("okf.toml"),
        "config_version = 1\nbundle_root = \"docs\"\n\n[paths]\nskip_names = [\"vendor\"]\ngenerated = [\"generated/**\"]\n\n[[type_rules]]\npath = \"typed/**\"\ntype = \"Reference\"\n",
    );
    write(
        &root.join("docs/typed/shared.md"),
        "---\ntype: Reference\n---\n\n# Shared\n",
    );
    git(root, &["add", "."]);
    git(root, &["commit", "--quiet", "-m", "base"]);
    git(root, &["update-ref", "refs/remotes/origin/main", "HEAD"]);
    git(
        root,
        &[
            "symbolic-ref",
            "refs/remotes/origin/HEAD",
            "refs/remotes/origin/main",
        ],
    );
}

#[test]
fn a_repository_root_bundle_is_surveyed() {
    let root = Scratch::new("root-bundle");
    git(root.path(), &["init", "--quiet", "--initial-branch=main"]);
    git(
        root.path(),
        &["config", "user.email", "fixture@example.invalid"],
    );
    git(root.path(), &["config", "user.name", "Fixture"]);
    write(
        &root.path().join("okf.toml"),
        "config_version = 1\nbundle_root = \".\"\n\n[[type_rules]]\npath = \"typed/**\"\ntype = \"Reference\"\n",
    );
    git(root.path(), &["add", "."]);
    git(root.path(), &["commit", "--quiet", "-m", "base"]);
    git(root.path(), &["switch", "--quiet", "-c", "topic"]);
    write(&root.path().join("typed/plain.md"), "# Plain\n");
    git(root.path(), &["add", "."]);
    git(root.path(), &["commit", "--quiet", "-m", "topic"]);
    git(
        root.path(),
        &["update-ref", "refs/remotes/origin/topic", "HEAD"],
    );
    git(root.path(), &["switch", "--quiet", "main"]);

    let output = run(root.path(), &["--survey-branches"]);

    assert!(output.status.success());
    assert_eq!(
        String::from_utf8_lossy(&output.stdout),
        "origin/topic:\n  would fail\ttyped/plain.md\n"
    );
}

#[test]
fn survey_uses_remote_refs_and_classifies_only_branch_only_findings() {
    let root = Scratch::new("branches");
    initialize(root.path());
    git(root.path(), &["switch", "--quiet", "-c", "topic"]);
    write(&root.path().join("docs/orphan.md"), "# Orphan\n");
    write(
        &root.path().join("docs/generated/report.md"),
        "# Generated by path\n",
    );
    write(
        &root.path().join("docs/typed/frontmatter.md"),
        "---\ngenerated: { by: fixture/1, at: 2026-08-29 }\n---\n\n# Generated frontmatter\n",
    );
    write(
        &root.path().join("docs/typed/marker.md"),
        "<!-- DO NOT EDIT -->\n# Generated marker\n",
    );
    write(
        &root.path().join("docs/typed/plain.md"),
        "# Missing frontmatter\n",
    );
    write(
        &root.path().join("docs/typed/clean.md"),
        "---\ntype: Reference\n---\n\n# Clean\n",
    );
    write(&root.path().join("docs/.hidden/ignored.md"), "# Hidden\n");
    write(
        &root.path().join("docs/vendor/ignored.md"),
        "# Configured skip\n",
    );
    write(&root.path().join("outside.md"), "# Outside bundle\n");
    git(root.path(), &["add", "."]);
    git(root.path(), &["commit", "--quiet", "-m", "topic"]);
    git(
        root.path(),
        &["update-ref", "refs/remotes/origin/topic", "HEAD"],
    );
    git(
        root.path(),
        &[
            "symbolic-ref",
            "refs/remotes/origin/HEAD",
            "refs/remotes/origin/topic",
        ],
    );
    git(root.path(), &["switch", "--quiet", "main"]);

    let output = run(&root.path().join("docs"), &["--survey-branches"]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(output.status.success(), "{stdout}");
    assert_eq!(
        stdout,
        "origin/topic:\n  generated\tgenerated/report.md\n  untypable\torphan.md\n  generated\ttyped/frontmatter.md\n  generated\ttyped/marker.md\n  would fail\ttyped/plain.md\n"
    );
    assert_eq!(git(root.path(), &["branch", "--show-current"]), "main");
    assert!(git(root.path(), &["status", "--porcelain"]).is_empty());
}

#[test]
fn a_repository_with_no_branch_findings_prints_nothing() {
    let root = Scratch::new("clean");
    initialize(root.path());

    let output = run(root.path(), &["--survey-branches"]);

    assert!(output.status.success());
    assert!(output.stdout.is_empty());
    assert!(output.stderr.is_empty());
}

#[test]
fn the_survey_flag_is_required_once() {
    let root = Scratch::new("usage");
    initialize(root.path());

    for args in [Vec::new(), vec!["--survey-branches", "--survey-branches"]] {
        let output = run(root.path(), &args);
        assert!(!output.status.success());
        assert!(String::from_utf8_lossy(&output.stderr).contains("usage: okf-adopt"));
    }
}
