//! The generated half of a tenant site: `hugo.toml`, the shared files, the
//! build lock, and the check that the raw markdown really is byte-identical.
//!
//! `hugo.toml` is derived from `site.toml` on every run rather than being a
//! tracked file each tenant edits, and that is a deliberate move away from the
//! obvious arrangement. The reason is [`taxonomies`]: Hugo's `[taxonomies]`
//! value is the front-matter key it looks for and *not* a plural of it, so a
//! single wrong character emits zero term pages with no warning and no error
//! and a successful build. A silent failure that four tenants could each
//! introduce independently belongs in one generated file with one fixture
//! behind it, not in four hand-edited ones.
//!
//! What a tenant chooses — its title, its base URL, its bundles — stays in
//! `site.toml`, which the tenant owns.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use crate::assemble::AssembleError;
use crate::hugopath::url_segment;
use crate::manifest::Manifest;

/// The taxonomies every tenant declares.
///
/// Key and value are the same word on purpose, and it is the trap this whole
/// module exists to close: the value is the front-matter key Hugo reads. Write
/// `team = "teams"` and Hugo looks for a `teams:` key, finds none in any
/// document, and emits no term pages at all while reporting success.
///
/// `client` is here and deliberately does not group across tenants, because
/// tenants are separate builds and a cross-client page must not be
/// constructible even by accident.
pub const TAXONOMIES: &[&str] = &["team", "project", "system", "client"];

fn io(context: String) -> impl FnOnce(std::io::Error) -> AssembleError {
    move |source| AssembleError::Io { context, source }
}

/// Write the layouts, the stylesheet and the recipes into the site tree.
///
/// # Errors
///
/// Fails when any of them cannot be written.
pub fn write_shared(root: &Path) -> Result<(), AssembleError> {
    for file in crate::layouts::LAYOUTS
        .iter()
        .chain(crate::layouts::SHARED.iter())
    {
        let path = root.join(file.path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(io(format!("creating {}", parent.display())))?;
        }
        std::fs::write(&path, file.contents).map_err(io(format!("writing {}", path.display())))?;
    }
    Ok(())
}

/// Generate `hugo.toml` from the manifest.
///
/// # Errors
///
/// Fails when the file cannot be written.
pub fn write_hugo_config(
    manifest: &Manifest,
    root: &Path,
    local: &[String],
) -> Result<(), AssembleError> {
    let taxonomies = TAXONOMIES.iter().fold(String::new(), |mut acc, name| {
        acc.push_str(name);
        acc.push_str(" = \"");
        acc.push_str(name);
        acc.push_str("\"\n");
        acc
    });
    let locals = if local.is_empty() {
        String::new()
    } else {
        let names: Vec<String> = local.iter().map(|id| toml_string(id)).collect();
        format!("okf_local_bundles = [{}]\n", names.join(", "))
    };
    let out = format!(
        "# Generated by okf-assemble from site.toml. Edit site.toml.\n\
         #\n\
         # Regenerated on every build, so a fix to the generator reaches every\n\
         # tenant by rolling one flake input forward.\n\
         \n\
         baseURL = {base_url}\n\
         title = {title}\n\
         locale = \"en-US\"\n\
         \n\
         # A section title is the directory's own title, never a pluralised or\n\
         # capitalised guess at one.\n\
         pluralizeListTitles = false\n\
         capitalizeListTitles = false\n\
         \n\
         # The value is the front-matter key Hugo reads, not a plural of the\n\
         # key. `team = \"teams\"` builds cleanly and emits nothing.\n\
         [taxonomies]\n\
         {taxonomies}\
         {markup}\
         {outputs}\
         \n[params]\n\
         description = {description}\n\
         tenant = {tenant}\n\
         {locals}",
        base_url = toml_string(&manifest.site.base_url),
        title = toml_string(&manifest.site.title),
        taxonomies = taxonomies,
        markup = markup_section(),
        outputs = output_section(),
        description = toml_string(&manifest.site.description),
        tenant = toml_string(&manifest.tenant),
        locals = locals,
    );
    let path = root.join("hugo.toml");
    std::fs::write(&path, out).map_err(io(format!("writing {}", path.display())))
}

fn markup_section() -> String {
    "\n# Raw HTML in a document renders. An engagement corpus is full of angle\n\
     # brackets and mid-line hashes, and rejecting them would be the site\n\
     # gating on document quality, which is the repository's job and not this\n\
     # build's.\n\
     [markup.goldmark.renderer]\n\
     unsafe = true\n\
     \n\
     # Chroma runs at build time, so no highlighting JavaScript ships and a\n\
     # page renders correctly with JavaScript off. Classes rather than inline\n\
     # styles, so one stylesheet covers both themes.\n\
     [markup.highlight]\n\
     noClasses = false\n\
     lineNos = false\n\
     \n\
     [markup.tableOfContents]\n\
     startLevel = 2\n\
     endLevel = 4\n"
        .to_owned()
}

fn output_section() -> String {
    "\n# The machine surface. `okfmarkdown` puts the source bytes at\n\
     # /<path>/index.md beside the HTML; `index.json` is the retrieval entry\n\
     # point; `llms.txt` is the reading list an agent fetches first, and it\n\
     # sits on term pages too so /team/<x>/llms.txt is a cross-bundle list.\n\
     [outputFormats.OkfMarkdown]\n\
     mediaType = \"text/markdown\"\n\
     suffix = \"md\"\n\
     isPlainText = true\n\
     \n\
     [outputFormats.OkfIndexJson]\n\
     mediaType = \"application/json\"\n\
     baseName = \"index\"\n\
     suffix = \"json\"\n\
     isPlainText = true\n\
     \n\
     [outputFormats.LlmsTxt]\n\
     mediaType = \"text/plain\"\n\
     baseName = \"llms\"\n\
     suffix = \"txt\"\n\
     isPlainText = true\n\
     \n\
     [outputs]\n\
     home = [\"html\", \"okfmarkdown\", \"okfindexjson\", \"llmstxt\"]\n\
     section = [\"html\", \"okfmarkdown\", \"llmstxt\"]\n\
     page = [\"html\", \"okfmarkdown\"]\n\
     term = [\"html\", \"llmstxt\"]\n\
     taxonomy = [\"html\"]\n"
        .to_owned()
}

/// What this build was built from, served at `/build-lock.json`.
///
/// No timestamp, on purpose. The same manifest and the same toolchain have to
/// produce a byte-identical `public/`, which is one of Phase 4's exit
/// criteria, and a generated clock reading would break that on the first run.
///
/// # Errors
///
/// Fails when the file cannot be written.
pub fn write_build_lock(manifest: &Manifest, root: &Path) -> Result<(), AssembleError> {
    let bundles = manifest
        .bundles
        .iter()
        .map(|bundle| {
            format!(
                "    {{\"id\": {}, \"repo\": {}, \"ref\": {}, \"rev\": {}, \"subdir\": {}}}",
                json_string(&bundle.id),
                json_string(&bundle.repo),
                json_string(&bundle.git_ref),
                json_string(&bundle.rev),
                json_string(&bundle.subdir),
            )
        })
        .collect::<Vec<String>>()
        .join(",\n");
    let body = format!(
        "{{\n  \"tenant\": {},\n  \"okf_tools\": {},\n  \"hugo\": {},\n  \"pagefind\": {},\n  \"bundles\": [\n{}\n  ]\n}}\n",
        json_string(&manifest.tenant),
        json_string(&tool_version("OKF_TOOLS_REV", env!("CARGO_PKG_VERSION"))),
        json_string(&program_version("hugo", &["version"])),
        json_string(&program_version("pagefind", &["--version"])),
        bundles,
    );
    let dest = root.join("static");
    std::fs::create_dir_all(&dest).map_err(io(format!("creating {}", dest.display())))?;
    let path = dest.join("build-lock.json");
    std::fs::write(&path, body).map_err(io(format!("writing {}", path.display())))
}

fn tool_version(variable: &str, fallback: &str) -> String {
    std::env::var(variable).unwrap_or_else(|_| fallback.to_owned())
}

fn program_version(program: &str, args: &[&str]) -> String {
    crate::assemble::capture(program, args).unwrap_or_else(|| "unknown".to_owned())
}

/// One rendered page and the assembled source it came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pair {
    pub rendered: String,
    pub source: String,
}

#[derive(Debug, Default)]
pub struct RawReport {
    /// Source pages that rendered both an HTML page and a raw one.
    pub compared: usize,
    /// Source pages whose raw markdown differs from the source bytes.
    pub differing: Vec<Pair>,
    /// Source pages with no raw markdown beside them.
    pub missing_raw: Vec<String>,
    /// Source pages with no HTML page beside them.
    pub missing_html: Vec<String>,
    /// Raw markdown under `public/` that no source explains.
    pub unmatched: Vec<String>,
}

impl RawReport {
    /// Every source page rendered both ways, and the raw half is byte-equal.
    #[must_use]
    pub fn is_clean(&self) -> bool {
        self.differing.is_empty()
            && self.missing_raw.is_empty()
            && self.missing_html.is_empty()
            && self.unmatched.is_empty()
            && self.compared > 0
    }
}

/// Compare every assembled source page against what Hugo rendered from it.
///
/// This is the gate that keeps the machine surface honest. `.RawContent` in a
/// template strips front matter and would quietly drop `type`, the one field
/// OKF requires; `os.ReadFile` returns the source bytes. The difference is
/// invisible on a rendered page and total to an agent, so it is measured on
/// every build rather than reasoned about.
///
/// The walk runs from `content/` rather than from `public/`, which is the only
/// direction that catches a page Hugo silently declined to render — the
/// leaf-bundle collision being exactly that failure. Taxonomy term pages have
/// no source and are therefore not expected to carry raw markdown; a raw page
/// with no source is reported the other way round.
///
/// One walk, one mapping. The reverse report is a set difference against the
/// page directories this walk already built, and not a second derivation that
/// rebuilds a content path from `public/`. See [`page_directory`] for why a
/// second derivation cannot be made to agree with the first.
///
/// # Errors
///
/// Fails when `content/` cannot be read or a pair cannot be compared.
pub fn verify_raw(root: &Path) -> Result<RawReport, AssembleError> {
    let public = root.join("public");
    let content = root.join("content");
    let mut report = RawReport::default();
    let mut expected: BTreeSet<PathBuf> = BTreeSet::new();

    for source in crate::walk::markdown_files(&content, &[]) {
        let relative = source.strip_prefix(&content).unwrap_or(&source);
        let page_dir = page_directory(relative);
        let rendered = public.join(&page_dir).join("index.md");
        let shown = crate::walk::to_posix(relative);
        // Expected whether or not Hugo wrote it: a page it declined to render
        // is a missing page, never an unexplained one.
        expected.insert(page_dir.clone());
        if !public.join(&page_dir).join("index.html").is_file() {
            report.missing_html.push(shown.clone());
        }
        if !rendered.is_file() {
            report.missing_raw.push(shown);
            continue;
        }
        let left =
            std::fs::read(&rendered).map_err(io(format!("reading {}", rendered.display())))?;
        let right = std::fs::read(&source).map_err(io(format!("reading {}", source.display())))?;
        report.compared = report.compared.saturating_add(1);
        if left != right {
            report.differing.push(Pair {
                rendered: crate::walk::to_posix(&page_dir),
                source: shown,
            });
        }
    }

    collect_unmatched(&public, &expected, &mut report);
    report.differing.sort_by(|a, b| a.rendered.cmp(&b.rendered));
    report.missing_raw.sort();
    report.missing_html.sort();
    report.unmatched.sort();
    Ok(report)
}

/// Where Hugo publishes the page assembled from this source file.
///
/// This is the only derivation of the content-to-public mapping in the
/// verifier, and [`collect_unmatched`] is a set difference against what it
/// returns rather than a second derivation running the other way. A published
/// segment cannot be un-transformed: `readme` could have come from `README`,
/// `ReadMe` or `readme`, and `release-notes-draft` from any of several dozen
/// names. So a reverse pass that rebuilds a content path is always free to
/// disagree with the forward one, and when it does, one page is reported
/// missing and unexplained at the same time — a false failure that looks
/// exactly like a real one.
fn page_directory(relative: &Path) -> PathBuf {
    let parent = relative.parent().unwrap_or(Path::new(""));
    let mut segments: Vec<String> = parent
        .components()
        .map(|part| url_segment(&part.as_os_str().to_string_lossy()))
        .collect();
    // A section listing publishes at its own directory; every other page
    // publishes at a directory named for its stem.
    if let Some(name) = relative.file_name().and_then(|n| n.to_str()) {
        if name != "_index.md" {
            segments.push(url_segment(name.strip_suffix(".md").unwrap_or(name)));
        }
    }
    // A segment can sanitise away to nothing, and Hugo then publishes the page
    // at its parent. Measured with a page named `Ⅻ.md`, which Hugo published
    // at its section's own URL.
    segments.retain(|segment| !segment.is_empty());
    segments.into_iter().collect()
}

/// Raw markdown under `public/` that no source explains.
///
/// `expected` is what the forward walk derived, so this is a set difference
/// and not a second opinion.
fn collect_unmatched(public: &Path, expected: &BTreeSet<PathBuf>, report: &mut RawReport) {
    let mut stack = vec![public.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if path.file_name().is_none_or(|n| n != "pagefind") {
                    stack.push(path);
                }
                continue;
            }
            if path.file_name().is_none_or(|n| n != "index.md") {
                continue;
            }
            let relative = path.strip_prefix(public).unwrap_or(&path);
            let page_dir = relative.parent().unwrap_or(Path::new(""));
            if !expected.contains(page_dir) {
                report.unmatched.push(crate::walk::to_posix(relative));
            }
        }
    }
}

/// A TOML basic string, which needs no knowledge of what is inside it.
#[must_use]
pub fn toml_string(value: &str) -> String {
    format!("\"{}\"", escape(value))
}

/// A JSON string, escaped the same way.
#[must_use]
pub fn json_string(value: &str) -> String {
    format!("\"{}\"", escape(value))
}

fn escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            control if control < ' ' => {
                let escaped = format!("\\u{:04x}", u32::from(control));
                out.push_str(&escaped);
            }
            other => out.push(other),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The single measured trap this module exists to close, asserted rather
    /// than commented: key and value are the same word.
    #[test]
    fn every_taxonomy_maps_a_key_to_itself() {
        let manifest = Manifest {
            tenant: "t".to_owned(),
            ..Manifest::default()
        };
        let dir = std::env::temp_dir().join(format!("okf-hugo-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        assert!(write_hugo_config(&manifest, &dir, &[]).is_ok());
        let text = std::fs::read_to_string(dir.join("hugo.toml")).unwrap_or_default();
        // The declarations only, so the comment warning about the plural does
        // not satisfy the assertion that warns about it.
        let block: String = text
            .split("[taxonomies]\n")
            .nth(1)
            .unwrap_or_default()
            .lines()
            .take_while(|line| !line.is_empty())
            .collect::<Vec<&str>>()
            .join("\n");
        for name in TAXONOMIES {
            assert!(block.contains(&format!("{name} = \"{name}\"")), "{block}");
            assert!(!block.contains(&format!("{name} = \"{name}s\"")), "{block}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_build_lock_carries_no_clock_reading() {
        let manifest = Manifest {
            tenant: "t".to_owned(),
            bundles: vec![crate::manifest::Bundle {
                id: "b".to_owned(),
                repo: "https://example.invalid/b.git".to_owned(),
                git_ref: "refs/heads/main".to_owned(),
                rev: "a".repeat(40),
                subdir: ".".to_owned(),
                credential: String::new(),
                site_absolute_base: String::new(),
            }],
            ..Manifest::default()
        };
        let dir = std::env::temp_dir().join(format!("okf-lock-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        assert!(write_build_lock(&manifest, &dir).is_ok());
        let text = std::fs::read_to_string(dir.join("static/build-lock.json")).unwrap_or_default();
        assert!(text.contains(&"a".repeat(40)), "{text}");
        for word in ["generated_at", "timestamp", "built_at"] {
            assert!(!text.contains(word), "{text}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A run that compared nothing is not a clean run: a gate pointed at an
    /// empty tree otherwise reports success, which is the failure the whole
    /// assembly step exists to catch.
    #[test]
    fn a_raw_report_with_nothing_compared_is_not_clean() {
        assert!(!RawReport::default().is_clean());
        assert!(
            RawReport {
                compared: 2,
                ..RawReport::default()
            }
            .is_clean()
        );
        assert!(
            !RawReport {
                compared: 2,
                missing_html: vec!["a.md".to_owned()],
                ..RawReport::default()
            }
            .is_clean()
        );
    }

    #[test]
    fn a_section_index_publishes_at_its_directory_and_a_page_at_its_stem() {
        assert_eq!(page_directory(Path::new("a/_index.md")), Path::new("a"));
        assert_eq!(page_directory(Path::new("a/b.md")), Path::new("a/b"));
        assert_eq!(page_directory(Path::new("_index.md")), Path::new(""));
    }

    #[test]
    fn a_capitalised_directory_and_a_capitalised_stem_publish_lowercased() {
        assert_eq!(
            page_directory(Path::new("lane-cast/Documentation/README.md")),
            Path::new("lane-cast/documentation/readme")
        );
        assert_eq!(
            page_directory(Path::new("lane-cast/Documentation/_index.md")),
            Path::new("lane-cast/documentation")
        );
    }

    /// A segment that sanitises away to nothing leaves the page at its
    /// parent, which is where Hugo put the measured one.
    #[test]
    fn a_segment_that_sanitises_to_nothing_drops_out_of_the_path() {
        assert_eq!(page_directory(Path::new("p/\u{216b}.md")), Path::new("p"));
    }

    /// The synthetic negative control, kept after the real one was fixed.
    ///
    /// A page that is really absent is reported once, as missing, and never
    /// also as unexplained. Reporting both is what a second derivation of the
    /// mapping does, and it is what made this gate cry wolf.
    #[test]
    fn a_page_is_never_both_missing_and_unexplained() {
        let root = std::env::temp_dir().join(format!("okf-raw-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let write = |path: &str, body: &str| {
            let full = root.join(path);
            if let Some(parent) = full.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let _ = std::fs::write(full, body);
        };

        write("content/_index.md", "home\n");
        write("content/Documentation/_index.md", "section\n");
        write("content/Documentation/README.md", "readme\n");
        write("public/index.md", "home\n");
        write("public/index.html", "");
        write("public/documentation/index.md", "section\n");
        write("public/documentation/index.html", "");
        // Hugo declined to render this one, and nothing else explains it.
        let report = verify_raw(&root).unwrap_or_default();
        assert_eq!(report.missing_raw, ["Documentation/README.md"]);
        assert!(report.unmatched.is_empty(), "{:?}", report.unmatched);
        assert_eq!(report.compared, 2);

        // Now it renders, and the report is clean.
        write("public/documentation/readme/index.md", "readme\n");
        write("public/documentation/readme/index.html", "");
        let report = verify_raw(&root).unwrap_or_default();
        assert!(report.is_clean(), "{report:?}");
        assert_eq!(report.compared, 3);

        // A raw page with no source at all is still reported.
        write("public/stray/index.md", "?\n");
        let report = verify_raw(&root).unwrap_or_default();
        assert_eq!(report.unmatched, ["stray/index.md"]);
        assert!(report.missing_raw.is_empty(), "{:?}", report.missing_raw);

        let _ = std::fs::remove_dir_all(&root);
    }
}
